spring.application.name=minha-app
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=meu-grupo
spring.kafka.consumer.auto-offset-reset=earliest
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/devops-lab
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/devops-lab/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG